<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>mac</string>
    </array>

<!--     <key>foldingStartMarker</key>
    <string>/\*\*|\{\s*$</string>

    <key>foldingStopMarker</key>
    <string>\*\*/|^\s*\}</string>

    <key>keyEquivalent</key>
    <string>^~U</string>
 -->
    <key>name</key>
    <string>RStyle</string>
    <key>patterns</key>
    <array>
        <!--  -->
        <!-- /* ... */ -->
        <dict>
            <key>begin</key>
            <string>/\*</string>

            <key>captures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.source.mac</string>
                </dict>
            </dict>

            <key>patterns</key>
            <array>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>constant.language.comment.source.mac</string>
                        </dict>

                        <key>2</key>
                        <dict>
                            <key>name</key> <!-- TODO: add variable entity highlighting -->
                            <string>constant.language.comment.source.mac</string>
                        </dict>

                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>constant.language.comment.source.mac</string>
                        </dict>
                    </dict>

                    <key>match</key>
                    <string>(?i:(@parameter|@param)\s*|@)([a-z-A-Z_][a-z-A-Z_0-9]+)|(?i:(FILE|COPYRIGHT|DESCRIPTION|PROGRAMMED BY|CREATION DATE|LAST UPDATE|TODO|HACK|FIXME|WARNING|NOTE|INFO|HELP))\s*:</string>
                </dict>
            </array>

            <key>end</key>
            <string>\*/</string>

            <key>name</key>
            <string>comment.block.source.mac</string>
        </dict>

        <!-- ... */ ... \n -->
        <dict>
            <key>match</key>
            <string>\*/.*\n</string>

            <key>name</key>
            <string>invalid.illegal.stray-comment-end.source.mac</string>
        </dict>

        <!-- // ... \n -->
        <dict>
            <key>begin</key>
            <string>//</string>


            <key>end</key>
            <string>$\n?</string>

            <key>name</key>
            <string>comment.line.double-slash.source.mac</string>

            <key>patterns</key>
            <array>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>invalid.deprecated.needfix.source.mac</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>constant.language.comment.source.mac</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key> <!-- TODO: add variable entity highlighting -->
                            <string>constant.language.comment.source.mac</string>
                        </dict>
                        <key>4</key>
                        <dict>
                            <key>name</key>
                            <string>constant.language.comment.source.mac</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(!.*\n)|(?i:(@parameter|@param)\s*|@)([a-z-A-Z_][a-z-A-Z_0-9]+)|(?i:(FILE|COPYRIGHT|DESCRIPTION|PROGRAMMED BY|CREATION DATE|LAST UPDATE|TODO|HACK|FIXME|WARNING|NOTE|INFO|HELP))\s*:</string>
                </dict>
            </array>
        </dict>
        <!--  -->
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>constant.numeric.mac</string>
                </dict>
            </dict>
            <key>comment</key>
            <string>Tab stops like $1, $2...</string>
            <key>match</key>
            <string>\$(\d+)</string>
            <key>name</key>
            <string>keyword.mac</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>(?i)^\s*(import)\s+</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.control.import.mac</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(\;)</string>
            <key>endCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.end.mac</string>
                </dict>
            </dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>import.file.mac</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>\"*(([\w\d\s])*(.mac)*)\"?\s*(,||;)</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>$self</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b(Null|NullObj)\b</string>
            <key>name</key>
            <string>constant.language.mac</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\btrue\b</string>
            <key>name</key>
            <string>constant.language.boolean.true.mac</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\bfalse\b</string>
            <key>name</key>
            <string>constant.language.boolean.false.mac</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b(const)\b</string>
            <key>name</key>
            <string>storage.modifier.mac</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)(this)</string>
            <key>name</key>
            <string>constant.language.mac</string>
        </dict>
        <dict>
            <key>comment</key>
            <string>keyword operators that evaluate to True or False</string>
            <key>match</key>
            <string>(?i)\b(and|not|or)\b</string>
            <key>name</key>
            <string>keyword.operator.logical.mac</string>
        </dict>
        <dict>
            <key>comment</key>
            <string>magic variables which a class/module may have.</string>
            <key>match</key>
            <string>(?i)\b(private|local|debugbreak|file|weakref|cpwin)\b</string>
            <key>name</key>
            <string>keyword.control.mac</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\*|\-|\+|==|=|!=|&lt;=|&gt;=|&lt;&gt;|&lt;|&gt;</string>
            <key>name</key>
            <string>keyword.operator.mac</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\.</string>
            <key>name</key>
            <string>meta.delimiter.method.period.mac</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b((0(x|X)[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?))\b</string>
            <key>name</key>
            <string>constant.numeric.mac</string>
        </dict>
        <dict>
            <key>comment</key>
            <string>ключевые слова, которые формируют или прерывают цикл</string>
            <key>match</key>
            <string>(?i)\b(elif|else|for|if|while|break|continue|return|end)\b</string>
            <key>name</key>
            <string>keyword.control.flow.mac</string>
        </dict>
        <dict>
            <key>comment</key>
            <string>Стандартные процедуры ввода данных</string>
            <key>match</key>
            <string>(?i)\b(GetInt|GetDouble|GetMoney|GetString|GetStringR|GetDate|GetTRUE|GetTime)\b</string>
            <key>name</key>
            <string>support.function.in.mac</string>
        </dict>
        <dict>
            <key>comment</key>
            <string>Стандартные процедуры вывода</string>
            <key>match</key>
            <string>(?i)\b(Print|PrintLn|Message|SetOutput|SetColumn|FlushColumn|ClearColumn|SetDefPrec|SetOutHandler|GetPRNInfo|SetPRNInfo|SetDefMoneyPrec)\b</string>
            <key>name</key>
            <string>support.function.out.mac</string>
        </dict>
        <dict>
            <key>comment</key>
            <string>Процедуры преобразования типа</string>
            <key>match</key>
            <string>(?i)\b(Asize|CurToStrAlt|Date|DateSplit|Decimal|Double|DoubleL|DtTm|DtTmSplit|Floor|Int|MkStr|Money|MonName|NumToStr|Round|RubToStr|RubToStrAlt|SetAutoMoneyFloor|String|Time|TimeSplit|ValType)\b</string>
            <key>name</key>
            <string>support.function.exchange.type.mac</string>
        </dict>
        <dict>
            <key>comment</key>
            <string>Процедуры для работы со строками</string>
            <key>match</key>
            <string>(?i)\b(CodeFor|Index|StrBrk|StrFor|StrLen|StrLwr|StrSet|StrSplit|StrSplit2|StrSubst|StrUpr|SubStr|ToANSI|ToOEM|Trim)\b</string>
            <key>name</key>
            <string>support.function.string.mac</string>
        </dict>
        <dict>
            <key>comment</key>
            <string>Параметры процедур</string>
            <key>match</key>
            <string>(?i)\b(GetParm|SetParm|Parmcount)\b</string>
            <key>name</key>
            <string>support.function.param.mac</string>
        </dict>
        <dict>
            <key>comment</key>
            <string>Математические процедуры</string>
            <key>match</key>
            <string>(?i)\b(Exp|Log|Log10|Pow|Sqrt|Abs|Min|Max|Mod)\b</string>
            <key>name</key>
            <string>support.function.matematical.mac</string>
        </dict>
        <dict>
            <key>comment</key>
            <string>Процедуры управления файлами и каталогами</string>
            <key>match</key>
            <string>(?i)\b(CopyFile|GetCurDir|GetFileInfo|GetIniFileValue|MakeDir|RemoveDir|RemoveFile|RenameFile)\b</string>
            <key>name</key>
            <string>support.function.file.mac</string>
        </dict>
        <dict>
            <key>comment</key>
            <string>Процедура запуска внешних программ Run</string>
            <key>match</key>
            <string>(?i)\b(Run)\b</string>
            <key>name</key>
            <string>support.function.run.mac</string>
        </dict>
        <dict>
            <key>comment</key>
            <string>Процедура удаленного запуска макропрограмм CallRemoteRsl</string>
            <key>match</key>
            <string>(?i)\b(CallRemoteRsl)\b</string>
            <key>name</key>
            <string>support.function.remoterun.mac</string>
        </dict>
        <dict>
            <key>comment</key>
            <string>Процедуры для работы с классами и объектами</string>
            <key>match</key>
            <string>(?i)\b(CallR2M|record|ClrRmtOnRelease|GenAttach|GenClassName|GenGetProp|GenNumProps|GenObject|GenPropID|GenRun|GenSetProp|GetNamedChanel|IsEqClass|R2M)\b</string>
            <key>name</key>
            <string>support.function.calssobj.mac</string>
        </dict>
        <dict>
            <key>comment</key>
            <string>Прочие процедуры</string>
            <key>match</key>
            <string>(?i)\b(AddEvent|BegAction|EndAction|CmdArgs|CurrentLine|ClassKind|CheckBits|DateShift|InstLoadModule|ErrBox|ErrPrint|ExecExp|ExecMacro|ExecMacro2|ExecMacroFile|ExecMacroModule|Exit|FindPath|GetEnv|GetLangId|GetLocaleInfo|GetUIMode|GetSysDir|GetUserName|GCollect|IsSQL|MemSize|MergeFile|ModuleFileName|ModuleName|MsgBoxEx|PrintModule|PrintSymModule|PrintFiles|PrintRefs|PrintProps|PrintGlobs|PrintLocs|PrintStack|Random|ReplaceMacro|RunError|SetExitFlag|SplitFile|StrongRef|StartProg|SysGetProperty|SysPutProperty|Trace|UnderRCWHost|Version|ZeroValue|OnError)\b</string>
            <key>name</key>
            <string>support.function.other.mac</string>
        </dict>
        <dict>
            <key>comment</key>
            <string>Стандартные классы языка RSL</string>
            <key>match</key>
            <string>(?i)\b(TArray|TDirList|TRslChanel|TRcwSite|TRslEvHandler|TRslEvSourse|TRcwHost|TRsAxServer|TClrHost|TStream|TDbError|RslTimer)\b</string>
            <key>name</key>
            <string>class.language.mac</string>
        </dict>
        <dict>
            <key>comment</key>
            <string>Конструктор ActiveX-объектов</string>
            <key>match</key>
            <string>(?i)\b(activex)\b</string>
            <key>name</key>
            <string>class.language.activex.mac</string>
        </dict>
        <dict>
            <key>comment</key>
            <string>RS-Forms</string>
            <key>match</key>
            <string>(?i)\b(TControl|addHandler)\b</string>
            <key>name</key>
            <string>support.function.rsforms.mac</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#block-comments</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.mac</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(//).*$\n?</string>
            <key>name</key>
            <string>comment.line.double-slash.mac</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(\$)</string>
            <key>name</key>
            <string>invalid.mac</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>(?i)^\s*(private)?\s*(class)\s+((\()\s*([А-Яа-яA-Za-z_][А-Яа-яA-Za-z0-9_]*)\s*(\)))?(\/*.*\*\/)*\s*(?=[А-Яа-яA-Za-z_][А-Яа-яA-Za-z0-9_]*)</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>storage.modifier.mac</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>storage.type.class.mac</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>entity.other.inherited-class.mac</string>
                </dict>
                <key>7</key>
                <dict>
                    <key>name</key>
                    <string>comment.block.mac</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(\))|(\s*$)|([:]\s*(\w*))</string>
            <key>endCaptures</key>
            <dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.section.class.begin.mac</string>
                </dict>
            </dict>
            <key>name</key>
            <string>meta.class.mac</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>(?=[А-Яа-яA-Za-z_][А-Яа-яA-Za-z0-9_]*)</string>
                    <key>contentName</key>
                    <string>entity.name.class.mac</string>
                    <key>end</key>
                    <string>(?![А-Яа-яA-Za-z0-9_])</string>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(\()</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.parameters.begin.mac</string>
                        </dict>
                    </dict>
                    <key>contentName</key>
                    <string>meta.class.parameters.mac</string>
                    <key>end</key>
                    <string>(\))</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>captures</key>
                            <dict>
                                <key>1</key>
                                <dict>
                                    <key>name</key>
                                    <string>variable.parameter.class.mac</string>
                                </dict>
                                <key>2</key>
                                <dict>
                                    <key>name</key>
                                    <string>punctuation.separator.parameters.mac</string>
                                </dict>
                                <key>3</key>
                                <dict>
                                    <key>name</key>
                                    <string>storage.type.variable.parameter.mac</string>
                                </dict>
                            </dict>
                            <key>match</key>
                            <string>([А-Яа-яa-zA-Z_][А-Яа-яa-zA-Z_0-9]*)\s*(([:]\s*(\w*))|([,]))?</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>$self</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>include</key>
                    <string>$self</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>(?i)^\s*((private|local)\s+)?(macro)\s+(\/*.*\*\/\s*)*(?=[А-Яа-яA-Za-z_][А-Яа-яA-Za-z0-9_]*)</string>
            <key>beginCaptures</key>
            <dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>storage.modifier.mac</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>storage.type.function.mac</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>comment.block.mac</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(\))|(\s*$)|([:]\s*(@?\w*))</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.parameters.end.mac</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>storage.type.variable.parameter.mac</string>
                </dict>
            </dict>
            <key>name</key>
            <string>meta.function.mac</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>(?i)(?=[А-Яа-яA-Za-z_][А-Яа-яA-Za-z0-9_]*)</string>
                    <key>contentName</key>
                    <string>entity.name.function.mac</string>
                    <key>end</key>
                    <string>(?![А-Яа-яA-Za-z0-9_])</string>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(\()</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.parameters.begin.mac</string>
                        </dict>
                    </dict>
                    <key>contentName</key>
                    <string>meta.function.parameters.mac</string>
                    <key>end</key>
                    <string>(\))</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>captures</key>
                            <dict>
                                <key>1</key>
                                <dict>
                                    <key>name</key>
                                    <string>variable.parameter.function.mac</string>
                                </dict>
                                <key>2</key>
                                <dict>
                                    <key>name</key>
                                    <string>punctuation.separator.parameters.mac</string>
                                </dict>
                                <key>4</key>
                                <dict>
                                    <key>name</key>
                                    <string>storage.type.variable.parameter.mac</string>
                                </dict>
                            </dict>
                            <key>match</key>
                            <string>(?i)([А-Яа-яa-zA-Z_][А-Яа-яa-zA-Z_0-9]*)\s*(([:]\s*(@?\w*))|([,]))?</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>$self</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>include</key>
                    <string>$self</string>
                </dict>
            </array>
        </dict>
        <!-- Variable -->
        <dict>
            <key>begin</key>
            <string>(?i)\s*((private|local)\s+)?(var)\s+</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>storage.modifier.mac</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>storage.type.var.mac</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(\;)</string>
            <key>endCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.parameters.end.mac</string>
                </dict>
            </dict>
            <key>name</key>
            <string>meta.variable.mac</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>(?i)(?=[А-Яа-яA-Za-z_][А-Яа-яA-Za-z0-9_]*)</string>
                    <key>contentName</key>
                    <string>variable.declare.name.mac</string>
                    <key>end</key>
                    <string>(?![А-Яа-яA-Za-z0-9_])</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\s*(:\s*\w+)</string>
                    <key>name</key>
                    <string>storage.type.variable.mac</string>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?i)\s*(=)\s*</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.operator.mac</string>
                        </dict>
                    </dict>
                    <key>contentName</key>
                    <string>value.mac</string>
                    <key>end</key>
                    <string>(?![А-Яа-яA-Za-z0-9_])</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>$self</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?i)(?=\()</string>
                    <key>contentName</key>
                    <string>parameters.value.mac</string>
                    <key>end</key>
                    <string>(?=\))</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>$self</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\s*(\.\s*\w+)</string>
                    <key>name</key>
                    <string>property.value.mac</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>$self</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>include</key>
                    <string>$self</string>
                </dict>
            </array>
        </dict>
        <!-- END Variable -->
        <dict>
            <key>begin</key>
            <string>(")</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.mac</string>
                </dict>
            </dict>
            <key>comment</key>
            <string>double quoted string</string>
            <key>end</key>
            <string>((?&lt;=")(")|")|(\n)</string>
            <key>endCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.mac</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>meta.empty-string.double.mac</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>invalid.illegal.unclosed-string.mac</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.single-line.raw.mac</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>([^\.])(\\\")([\s\w]*\.?[\w\s]*)(\\\")</string>
                    <key>name</key>
                    <string>constant.other.table-name.mac</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(`)</string>
                    <key>name</key>
                    <string>string.quoted.double.single-line.raw.mac</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(')</string>
                    <key>name</key>
                    <string>string.quoted.double.single-line.raw.mac</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(\#|--)?</string>
                    <key>name</key>
                    <string>string.quoted.double.single-line.raw.mac</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(\\x[0-9A-F]{2})|(\\[0-7]{3})|(\\\\)|(\\\")|(\\n)|(\\r)</string>
                    <key>name</key>
                    <string>constant.character.escape.mac</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>source.sql</string>
                </dict>
            </array>
        </dict>
    </array>
    <key>repository</key>
    <dict>
        <key>block-comments</key>
        <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.mac</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#block-comments</string>
                </dict>
            </array>
        </dict>
    </dict>
    <key>scopeName</key>
    <string>source.mac</string>
    <key>uuid</key>
    <string>f24766ec-8d6d-423b-8b09-3f9939e4ff02</string>
</dict>
</plist>
